/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package io.nitric

import io.nitric.resources.BucketPermission


class Library {
    fun main() {

        val bucket = Nitric.bucket("test").with(BucketPermission.Read)
        val api = Nitric.api("test")

        api.get("/test/:name") {
            bucket.file("test").write("test")
            it
        }

        Nitric.run()

    }
}
