//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/storage/v1/storage.proto

package io.nitric.proto.storage.v1;

@kotlin.jvm.JvmName("-initializestorageDeleteResponse")
inline fun storageDeleteResponse(block: io.nitric.proto.storage.v1.StorageDeleteResponseKt.Dsl.() -> kotlin.Unit): io.nitric.proto.storage.v1.StorageDeleteResponse =
  io.nitric.proto.storage.v1.StorageDeleteResponseKt.Dsl._create(io.nitric.proto.storage.v1.StorageDeleteResponse.newBuilder()).apply { block() }._build()
object StorageDeleteResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: io.nitric.proto.storage.v1.StorageDeleteResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.nitric.proto.storage.v1.StorageDeleteResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.nitric.proto.storage.v1.StorageDeleteResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun io.nitric.proto.storage.v1.StorageDeleteResponse.copy(block: io.nitric.proto.storage.v1.StorageDeleteResponseKt.Dsl.() -> kotlin.Unit): io.nitric.proto.storage.v1.StorageDeleteResponse =
  io.nitric.proto.storage.v1.StorageDeleteResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

