//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/faas/v1/faas.proto

package io.nitric.proto.faas.v1;

@kotlin.jvm.JvmName("-initializeapiWorker")
inline fun apiWorker(block: io.nitric.proto.faas.v1.ApiWorkerKt.Dsl.() -> kotlin.Unit): io.nitric.proto.faas.v1.ApiWorker =
  io.nitric.proto.faas.v1.ApiWorkerKt.Dsl._create(io.nitric.proto.faas.v1.ApiWorker.newBuilder()).apply { block() }._build()
object ApiWorkerKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: io.nitric.proto.faas.v1.ApiWorker.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.nitric.proto.faas.v1.ApiWorker.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.nitric.proto.faas.v1.ApiWorker = _builder.build()

    /**
     * <code>string api = 1;</code>
     */
    var api: kotlin.String
      @JvmName("getApi")
      get() = _builder.getApi()
      @JvmName("setApi")
      set(value) {
        _builder.setApi(value)
      }
    /**
     * <code>string api = 1;</code>
     */
    fun clearApi() {
      _builder.clearApi()
    }

    /**
     * <code>string path = 2;</code>
     */
    var path: kotlin.String
      @JvmName("getPath")
      get() = _builder.getPath()
      @JvmName("setPath")
      set(value) {
        _builder.setPath(value)
      }
    /**
     * <code>string path = 2;</code>
     */
    fun clearPath() {
      _builder.clearPath()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class MethodsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated string methods = 3;</code>
     * @return A list containing the methods.
     */
     val methods: com.google.protobuf.kotlin.DslList<kotlin.String, MethodsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getMethodsList()
      )
    /**
     * <code>repeated string methods = 3;</code>
     * @param value The methods to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addMethods")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, MethodsProxy>.add(value: kotlin.String) {
      _builder.addMethods(value)
    }
    /**
     * <code>repeated string methods = 3;</code>
     * @param value The methods to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignMethods")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, MethodsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * <code>repeated string methods = 3;</code>
     * @param values The methods to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllMethods")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, MethodsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllMethods(values)
    }
    /**
     * <code>repeated string methods = 3;</code>
     * @param values The methods to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllMethods")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, MethodsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * <code>repeated string methods = 3;</code>
     * @param index The index to set the value at.
     * @param value The methods to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setMethods")
    operator fun com.google.protobuf.kotlin.DslList<kotlin.String, MethodsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setMethods(index, value)
    }/**
     * <code>repeated string methods = 3;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearMethods")
    fun com.google.protobuf.kotlin.DslList<kotlin.String, MethodsProxy>.clear() {
      _builder.clearMethods()
    }
    /**
     * <code>.nitric.faas.v1.ApiWorkerOptions options = 4;</code>
     */
    var options: io.nitric.proto.faas.v1.ApiWorkerOptions
      @JvmName("getOptions")
      get() = _builder.getOptions()
      @JvmName("setOptions")
      set(value) {
        _builder.setOptions(value)
      }
    /**
     * <code>.nitric.faas.v1.ApiWorkerOptions options = 4;</code>
     */
    fun clearOptions() {
      _builder.clearOptions()
    }
    /**
     * <code>.nitric.faas.v1.ApiWorkerOptions options = 4;</code>
     * @return Whether the options field is set.
     */
    fun hasOptions(): kotlin.Boolean {
      return _builder.hasOptions()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun io.nitric.proto.faas.v1.ApiWorker.copy(block: io.nitric.proto.faas.v1.ApiWorkerKt.Dsl.() -> kotlin.Unit): io.nitric.proto.faas.v1.ApiWorker =
  io.nitric.proto.faas.v1.ApiWorkerKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val io.nitric.proto.faas.v1.ApiWorkerOrBuilder.optionsOrNull: io.nitric.proto.faas.v1.ApiWorkerOptions?
  get() = if (hasOptions()) getOptions() else null

