//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/faas/v1/faas.proto

package io.nitric.proto.faas.v1;

@kotlin.jvm.JvmName("-initializeinitResponse")
inline fun initResponse(block: io.nitric.proto.faas.v1.InitResponseKt.Dsl.() -> kotlin.Unit): io.nitric.proto.faas.v1.InitResponse =
  io.nitric.proto.faas.v1.InitResponseKt.Dsl._create(io.nitric.proto.faas.v1.InitResponse.newBuilder()).apply { block() }._build()
object InitResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: io.nitric.proto.faas.v1.InitResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.nitric.proto.faas.v1.InitResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.nitric.proto.faas.v1.InitResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun io.nitric.proto.faas.v1.InitResponse.copy(block: io.nitric.proto.faas.v1.InitResponseKt.Dsl.() -> kotlin.Unit): io.nitric.proto.faas.v1.InitResponse =
  io.nitric.proto.faas.v1.InitResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

