// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/storage/v1/storage.proto

package io.nitric.proto.storage.v1;

public interface StorageListFilesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.storage.v1.StorageListFilesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bucket_name = 1;</code>
   * @return The bucketName.
   */
  java.lang.String getBucketName();
  /**
   * <code>string bucket_name = 1;</code>
   * @return The bytes for bucketName.
   */
  com.google.protobuf.ByteString
      getBucketNameBytes();

  /**
   * <code>string prefix = 2;</code>
   * @return The prefix.
   */
  java.lang.String getPrefix();
  /**
   * <code>string prefix = 2;</code>
   * @return The bytes for prefix.
   */
  com.google.protobuf.ByteString
      getPrefixBytes();
}
