//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/secret/v1/secret.proto

package io.nitric.proto.secret.v1;

@kotlin.jvm.JvmName("-initializesecretPutRequest")
inline fun secretPutRequest(block: io.nitric.proto.secret.v1.SecretPutRequestKt.Dsl.() -> kotlin.Unit): io.nitric.proto.secret.v1.SecretPutRequest =
  io.nitric.proto.secret.v1.SecretPutRequestKt.Dsl._create(io.nitric.proto.secret.v1.SecretPutRequest.newBuilder()).apply { block() }._build()
object SecretPutRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: io.nitric.proto.secret.v1.SecretPutRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.nitric.proto.secret.v1.SecretPutRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.nitric.proto.secret.v1.SecretPutRequest = _builder.build()

    /**
     * <pre>
     * The Secret to put to the Secret store
     * </pre>
     *
     * <code>.nitric.secret.v1.Secret secret = 1 [(.validate.rules) = { ... }</code>
     */
    var secret: io.nitric.proto.secret.v1.Secret
      @JvmName("getSecret")
      get() = _builder.getSecret()
      @JvmName("setSecret")
      set(value) {
        _builder.setSecret(value)
      }
    /**
     * <pre>
     * The Secret to put to the Secret store
     * </pre>
     *
     * <code>.nitric.secret.v1.Secret secret = 1 [(.validate.rules) = { ... }</code>
     */
    fun clearSecret() {
      _builder.clearSecret()
    }
    /**
     * <pre>
     * The Secret to put to the Secret store
     * </pre>
     *
     * <code>.nitric.secret.v1.Secret secret = 1 [(.validate.rules) = { ... }</code>
     * @return Whether the secret field is set.
     */
    fun hasSecret(): kotlin.Boolean {
      return _builder.hasSecret()
    }

    /**
     * <pre>
     * The value to assign to that secret
     * </pre>
     *
     * <code>bytes value = 2;</code>
     */
    var value: com.google.protobuf.ByteString
      @JvmName("getValue")
      get() = _builder.getValue()
      @JvmName("setValue")
      set(value) {
        _builder.setValue(value)
      }
    /**
     * <pre>
     * The value to assign to that secret
     * </pre>
     *
     * <code>bytes value = 2;</code>
     */
    fun clearValue() {
      _builder.clearValue()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun io.nitric.proto.secret.v1.SecretPutRequest.copy(block: io.nitric.proto.secret.v1.SecretPutRequestKt.Dsl.() -> kotlin.Unit): io.nitric.proto.secret.v1.SecretPutRequest =
  io.nitric.proto.secret.v1.SecretPutRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val io.nitric.proto.secret.v1.SecretPutRequestOrBuilder.secretOrNull: io.nitric.proto.secret.v1.Secret?
  get() = if (hasSecret()) getSecret() else null

