//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/secret/v1/secret.proto

package io.nitric.proto.secret.v1;

@kotlin.jvm.JvmName("-initializesecret")
inline fun secret(block: io.nitric.proto.secret.v1.SecretKt.Dsl.() -> kotlin.Unit): io.nitric.proto.secret.v1.Secret =
  io.nitric.proto.secret.v1.SecretKt.Dsl._create(io.nitric.proto.secret.v1.Secret.newBuilder()).apply { block() }._build()
object SecretKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: io.nitric.proto.secret.v1.Secret.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.nitric.proto.secret.v1.Secret.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.nitric.proto.secret.v1.Secret = _builder.build()

    /**
     * <pre>
     * The secret name
     * </pre>
     *
     * <code>string name = 1 [(.validate.rules) = { ... }</code>
     */
    var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <pre>
     * The secret name
     * </pre>
     *
     * <code>string name = 1 [(.validate.rules) = { ... }</code>
     */
    fun clearName() {
      _builder.clearName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun io.nitric.proto.secret.v1.Secret.copy(block: io.nitric.proto.secret.v1.SecretKt.Dsl.() -> kotlin.Unit): io.nitric.proto.secret.v1.Secret =
  io.nitric.proto.secret.v1.SecretKt.Dsl._create(this.toBuilder()).apply { block() }._build()

