//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/document/v1/document.proto

package io.nitric.proto.document.v1;

@kotlin.jvm.JvmName("-initializedocumentDeleteResponse")
inline fun documentDeleteResponse(block: io.nitric.proto.document.v1.DocumentDeleteResponseKt.Dsl.() -> kotlin.Unit): io.nitric.proto.document.v1.DocumentDeleteResponse =
  io.nitric.proto.document.v1.DocumentDeleteResponseKt.Dsl._create(io.nitric.proto.document.v1.DocumentDeleteResponse.newBuilder()).apply { block() }._build()
object DocumentDeleteResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: io.nitric.proto.document.v1.DocumentDeleteResponse.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.nitric.proto.document.v1.DocumentDeleteResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.nitric.proto.document.v1.DocumentDeleteResponse = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun io.nitric.proto.document.v1.DocumentDeleteResponse.copy(block: io.nitric.proto.document.v1.DocumentDeleteResponseKt.Dsl.() -> kotlin.Unit): io.nitric.proto.document.v1.DocumentDeleteResponse =
  io.nitric.proto.document.v1.DocumentDeleteResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

