import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.4.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    // id("org.jetbrains.kotlin.jvm") version "1.5.31"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    kotlin("jvm") version "1.6.21"

    // Apply the maven-publish plugin for publishing the final artifact
    `maven-publish`
}

group = "io.nitric"
version = "0.0.1"

java {
    withJavadocJar()
    withSourcesJar()
}

publishing {
    repositories {
        maven {

        }
    }

    publications {
        create<MavenPublication>("mavenJava"){
            groupId = "io.nitric"
            artifactId = "jvm-sdk"
            from(components["java"])
//            versionMapping{
//                usage("java-api") {
//                    fromResolutionOf("runtimeClassPath")
//                }
//                usage("java-runtime") {
//                    fromResolutionResult()
//                }
//            }
            pom {
                name.set("Nitric JVM SDK")
                description.set("")
                url.set("")

                licenses {
                    license {
                        name.set("")
                        url.set("")
                    }
                }
                developers {
                    developer {
                        id.set("nitric")
                        name.set("nitric")
                        email.set("maintainers@nitric.io")
                    }
                }
            }
        }
    }
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation("com.google.guava:guava:30.1.1-jre")

    // Kotlin co-routines lib
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.0")

    // Nitric base clients
    implementation("io.nitric:api:0.16.0")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api("org.apache.commons:commons-math3:3.6.1")

    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.2")
}
val compileKotlin: KotlinCompile by tasks
compileKotlin.kotlinOptions {
    jvmTarget = "1.8"
}
val compileTestKotlin: KotlinCompile by tasks
compileTestKotlin.kotlinOptions {
    jvmTarget = "1.8"
}