// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validate/validate.proto

package io.envoyproxy.pgv.validate;

/**
 * <pre>
 * AnyRules describe constraints applied exclusively to the
 * `google.protobuf.Any` well-known type
 * </pre>
 *
 * Protobuf type {@code validate.AnyRules}
 */
public final class AnyRules extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:validate.AnyRules)
    AnyRulesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AnyRules.newBuilder() to construct.
  private AnyRules(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AnyRules() {
    in_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    notIn_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AnyRules();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.envoyproxy.pgv.validate.Validate.internal_static_validate_AnyRules_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.envoyproxy.pgv.validate.Validate.internal_static_validate_AnyRules_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.envoyproxy.pgv.validate.AnyRules.class, io.envoyproxy.pgv.validate.AnyRules.Builder.class);
  }

  private int bitField0_;
  public static final int REQUIRED_FIELD_NUMBER = 1;
  private boolean required_;
  /**
   * <pre>
   * Required specifies that this field must be set
   * </pre>
   *
   * <code>optional bool required = 1;</code>
   * @return Whether the required field is set.
   */
  @java.lang.Override
  public boolean hasRequired() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Required specifies that this field must be set
   * </pre>
   *
   * <code>optional bool required = 1;</code>
   * @return The required.
   */
  @java.lang.Override
  public boolean getRequired() {
    return required_;
  }

  public static final int IN_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList in_;
  /**
   * <pre>
   * In specifies that this field's `type_url` must be equal to one of the
   * specified values.
   * </pre>
   *
   * <code>repeated string in = 2;</code>
   * @return A list containing the in.
   */
  public com.google.protobuf.ProtocolStringList
      getInList() {
    return in_;
  }
  /**
   * <pre>
   * In specifies that this field's `type_url` must be equal to one of the
   * specified values.
   * </pre>
   *
   * <code>repeated string in = 2;</code>
   * @return The count of in.
   */
  public int getInCount() {
    return in_.size();
  }
  /**
   * <pre>
   * In specifies that this field's `type_url` must be equal to one of the
   * specified values.
   * </pre>
   *
   * <code>repeated string in = 2;</code>
   * @param index The index of the element to return.
   * @return The in at the given index.
   */
  public java.lang.String getIn(int index) {
    return in_.get(index);
  }
  /**
   * <pre>
   * In specifies that this field's `type_url` must be equal to one of the
   * specified values.
   * </pre>
   *
   * <code>repeated string in = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the in at the given index.
   */
  public com.google.protobuf.ByteString
      getInBytes(int index) {
    return in_.getByteString(index);
  }

  public static final int NOT_IN_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList notIn_;
  /**
   * <pre>
   * NotIn specifies that this field's `type_url` must not be equal to any of
   * the specified values.
   * </pre>
   *
   * <code>repeated string not_in = 3;</code>
   * @return A list containing the notIn.
   */
  public com.google.protobuf.ProtocolStringList
      getNotInList() {
    return notIn_;
  }
  /**
   * <pre>
   * NotIn specifies that this field's `type_url` must not be equal to any of
   * the specified values.
   * </pre>
   *
   * <code>repeated string not_in = 3;</code>
   * @return The count of notIn.
   */
  public int getNotInCount() {
    return notIn_.size();
  }
  /**
   * <pre>
   * NotIn specifies that this field's `type_url` must not be equal to any of
   * the specified values.
   * </pre>
   *
   * <code>repeated string not_in = 3;</code>
   * @param index The index of the element to return.
   * @return The notIn at the given index.
   */
  public java.lang.String getNotIn(int index) {
    return notIn_.get(index);
  }
  /**
   * <pre>
   * NotIn specifies that this field's `type_url` must not be equal to any of
   * the specified values.
   * </pre>
   *
   * <code>repeated string not_in = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the notIn at the given index.
   */
  public com.google.protobuf.ByteString
      getNotInBytes(int index) {
    return notIn_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(1, required_);
    }
    for (int i = 0; i < in_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, in_.getRaw(i));
    }
    for (int i = 0; i < notIn_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, notIn_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, required_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < in_.size(); i++) {
        dataSize += computeStringSizeNoTag(in_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getInList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < notIn_.size(); i++) {
        dataSize += computeStringSizeNoTag(notIn_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getNotInList().size();
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.envoyproxy.pgv.validate.AnyRules)) {
      return super.equals(obj);
    }
    io.envoyproxy.pgv.validate.AnyRules other = (io.envoyproxy.pgv.validate.AnyRules) obj;

    if (hasRequired() != other.hasRequired()) return false;
    if (hasRequired()) {
      if (getRequired()
          != other.getRequired()) return false;
    }
    if (!getInList()
        .equals(other.getInList())) return false;
    if (!getNotInList()
        .equals(other.getNotInList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRequired()) {
      hash = (37 * hash) + REQUIRED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRequired());
    }
    if (getInCount() > 0) {
      hash = (37 * hash) + IN_FIELD_NUMBER;
      hash = (53 * hash) + getInList().hashCode();
    }
    if (getNotInCount() > 0) {
      hash = (37 * hash) + NOT_IN_FIELD_NUMBER;
      hash = (53 * hash) + getNotInList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.envoyproxy.pgv.validate.AnyRules parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.envoyproxy.pgv.validate.AnyRules parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.envoyproxy.pgv.validate.AnyRules parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.envoyproxy.pgv.validate.AnyRules parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.envoyproxy.pgv.validate.AnyRules parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.envoyproxy.pgv.validate.AnyRules parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.envoyproxy.pgv.validate.AnyRules parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.envoyproxy.pgv.validate.AnyRules parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.envoyproxy.pgv.validate.AnyRules parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.envoyproxy.pgv.validate.AnyRules parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.envoyproxy.pgv.validate.AnyRules parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.envoyproxy.pgv.validate.AnyRules parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.envoyproxy.pgv.validate.AnyRules prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * AnyRules describe constraints applied exclusively to the
   * `google.protobuf.Any` well-known type
   * </pre>
   *
   * Protobuf type {@code validate.AnyRules}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:validate.AnyRules)
      io.envoyproxy.pgv.validate.AnyRulesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.envoyproxy.pgv.validate.Validate.internal_static_validate_AnyRules_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.envoyproxy.pgv.validate.Validate.internal_static_validate_AnyRules_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.envoyproxy.pgv.validate.AnyRules.class, io.envoyproxy.pgv.validate.AnyRules.Builder.class);
    }

    // Construct using io.envoyproxy.pgv.validate.AnyRules.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      required_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      in_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      notIn_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.envoyproxy.pgv.validate.Validate.internal_static_validate_AnyRules_descriptor;
    }

    @java.lang.Override
    public io.envoyproxy.pgv.validate.AnyRules getDefaultInstanceForType() {
      return io.envoyproxy.pgv.validate.AnyRules.getDefaultInstance();
    }

    @java.lang.Override
    public io.envoyproxy.pgv.validate.AnyRules build() {
      io.envoyproxy.pgv.validate.AnyRules result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.envoyproxy.pgv.validate.AnyRules buildPartial() {
      io.envoyproxy.pgv.validate.AnyRules result = new io.envoyproxy.pgv.validate.AnyRules(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.required_ = required_;
        to_bitField0_ |= 0x00000001;
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        in_ = in_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.in_ = in_;
      if (((bitField0_ & 0x00000004) != 0)) {
        notIn_ = notIn_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.notIn_ = notIn_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.envoyproxy.pgv.validate.AnyRules) {
        return mergeFrom((io.envoyproxy.pgv.validate.AnyRules)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.envoyproxy.pgv.validate.AnyRules other) {
      if (other == io.envoyproxy.pgv.validate.AnyRules.getDefaultInstance()) return this;
      if (other.hasRequired()) {
        setRequired(other.getRequired());
      }
      if (!other.in_.isEmpty()) {
        if (in_.isEmpty()) {
          in_ = other.in_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureInIsMutable();
          in_.addAll(other.in_);
        }
        onChanged();
      }
      if (!other.notIn_.isEmpty()) {
        if (notIn_.isEmpty()) {
          notIn_ = other.notIn_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureNotInIsMutable();
          notIn_.addAll(other.notIn_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              required_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              ensureInIsMutable();
              in_.add(bs);
              break;
            } // case 18
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              ensureNotInIsMutable();
              notIn_.add(bs);
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean required_ ;
    /**
     * <pre>
     * Required specifies that this field must be set
     * </pre>
     *
     * <code>optional bool required = 1;</code>
     * @return Whether the required field is set.
     */
    @java.lang.Override
    public boolean hasRequired() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Required specifies that this field must be set
     * </pre>
     *
     * <code>optional bool required = 1;</code>
     * @return The required.
     */
    @java.lang.Override
    public boolean getRequired() {
      return required_;
    }
    /**
     * <pre>
     * Required specifies that this field must be set
     * </pre>
     *
     * <code>optional bool required = 1;</code>
     * @param value The required to set.
     * @return This builder for chaining.
     */
    public Builder setRequired(boolean value) {
      bitField0_ |= 0x00000001;
      required_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required specifies that this field must be set
     * </pre>
     *
     * <code>optional bool required = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequired() {
      bitField0_ = (bitField0_ & ~0x00000001);
      required_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList in_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureInIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        in_ = new com.google.protobuf.LazyStringArrayList(in_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * In specifies that this field's `type_url` must be equal to one of the
     * specified values.
     * </pre>
     *
     * <code>repeated string in = 2;</code>
     * @return A list containing the in.
     */
    public com.google.protobuf.ProtocolStringList
        getInList() {
      return in_.getUnmodifiableView();
    }
    /**
     * <pre>
     * In specifies that this field's `type_url` must be equal to one of the
     * specified values.
     * </pre>
     *
     * <code>repeated string in = 2;</code>
     * @return The count of in.
     */
    public int getInCount() {
      return in_.size();
    }
    /**
     * <pre>
     * In specifies that this field's `type_url` must be equal to one of the
     * specified values.
     * </pre>
     *
     * <code>repeated string in = 2;</code>
     * @param index The index of the element to return.
     * @return The in at the given index.
     */
    public java.lang.String getIn(int index) {
      return in_.get(index);
    }
    /**
     * <pre>
     * In specifies that this field's `type_url` must be equal to one of the
     * specified values.
     * </pre>
     *
     * <code>repeated string in = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the in at the given index.
     */
    public com.google.protobuf.ByteString
        getInBytes(int index) {
      return in_.getByteString(index);
    }
    /**
     * <pre>
     * In specifies that this field's `type_url` must be equal to one of the
     * specified values.
     * </pre>
     *
     * <code>repeated string in = 2;</code>
     * @param index The index to set the value at.
     * @param value The in to set.
     * @return This builder for chaining.
     */
    public Builder setIn(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInIsMutable();
      in_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * In specifies that this field's `type_url` must be equal to one of the
     * specified values.
     * </pre>
     *
     * <code>repeated string in = 2;</code>
     * @param value The in to add.
     * @return This builder for chaining.
     */
    public Builder addIn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInIsMutable();
      in_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * In specifies that this field's `type_url` must be equal to one of the
     * specified values.
     * </pre>
     *
     * <code>repeated string in = 2;</code>
     * @param values The in to add.
     * @return This builder for chaining.
     */
    public Builder addAllIn(
        java.lang.Iterable<java.lang.String> values) {
      ensureInIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, in_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * In specifies that this field's `type_url` must be equal to one of the
     * specified values.
     * </pre>
     *
     * <code>repeated string in = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearIn() {
      in_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * In specifies that this field's `type_url` must be equal to one of the
     * specified values.
     * </pre>
     *
     * <code>repeated string in = 2;</code>
     * @param value The bytes of the in to add.
     * @return This builder for chaining.
     */
    public Builder addInBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureInIsMutable();
      in_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList notIn_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureNotInIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        notIn_ = new com.google.protobuf.LazyStringArrayList(notIn_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <pre>
     * NotIn specifies that this field's `type_url` must not be equal to any of
     * the specified values.
     * </pre>
     *
     * <code>repeated string not_in = 3;</code>
     * @return A list containing the notIn.
     */
    public com.google.protobuf.ProtocolStringList
        getNotInList() {
      return notIn_.getUnmodifiableView();
    }
    /**
     * <pre>
     * NotIn specifies that this field's `type_url` must not be equal to any of
     * the specified values.
     * </pre>
     *
     * <code>repeated string not_in = 3;</code>
     * @return The count of notIn.
     */
    public int getNotInCount() {
      return notIn_.size();
    }
    /**
     * <pre>
     * NotIn specifies that this field's `type_url` must not be equal to any of
     * the specified values.
     * </pre>
     *
     * <code>repeated string not_in = 3;</code>
     * @param index The index of the element to return.
     * @return The notIn at the given index.
     */
    public java.lang.String getNotIn(int index) {
      return notIn_.get(index);
    }
    /**
     * <pre>
     * NotIn specifies that this field's `type_url` must not be equal to any of
     * the specified values.
     * </pre>
     *
     * <code>repeated string not_in = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the notIn at the given index.
     */
    public com.google.protobuf.ByteString
        getNotInBytes(int index) {
      return notIn_.getByteString(index);
    }
    /**
     * <pre>
     * NotIn specifies that this field's `type_url` must not be equal to any of
     * the specified values.
     * </pre>
     *
     * <code>repeated string not_in = 3;</code>
     * @param index The index to set the value at.
     * @param value The notIn to set.
     * @return This builder for chaining.
     */
    public Builder setNotIn(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNotInIsMutable();
      notIn_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * NotIn specifies that this field's `type_url` must not be equal to any of
     * the specified values.
     * </pre>
     *
     * <code>repeated string not_in = 3;</code>
     * @param value The notIn to add.
     * @return This builder for chaining.
     */
    public Builder addNotIn(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNotInIsMutable();
      notIn_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * NotIn specifies that this field's `type_url` must not be equal to any of
     * the specified values.
     * </pre>
     *
     * <code>repeated string not_in = 3;</code>
     * @param values The notIn to add.
     * @return This builder for chaining.
     */
    public Builder addAllNotIn(
        java.lang.Iterable<java.lang.String> values) {
      ensureNotInIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, notIn_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * NotIn specifies that this field's `type_url` must not be equal to any of
     * the specified values.
     * </pre>
     *
     * <code>repeated string not_in = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearNotIn() {
      notIn_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * NotIn specifies that this field's `type_url` must not be equal to any of
     * the specified values.
     * </pre>
     *
     * <code>repeated string not_in = 3;</code>
     * @param value The bytes of the notIn to add.
     * @return This builder for chaining.
     */
    public Builder addNotInBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNotInIsMutable();
      notIn_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:validate.AnyRules)
  }

  // @@protoc_insertion_point(class_scope:validate.AnyRules)
  private static final io.envoyproxy.pgv.validate.AnyRules DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.envoyproxy.pgv.validate.AnyRules();
  }

  public static io.envoyproxy.pgv.validate.AnyRules getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<AnyRules>
      PARSER = new com.google.protobuf.AbstractParser<AnyRules>() {
    @java.lang.Override
    public AnyRules parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AnyRules> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnyRules> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.envoyproxy.pgv.validate.AnyRules getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

