// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validate/validate.proto

package io.envoyproxy.pgv.validate;

/**
 * <pre>
 * MessageRules describe the constraints applied to embedded message values.
 * For message-type fields, validation is performed recursively.
 * </pre>
 *
 * Protobuf type {@code validate.MessageRules}
 */
public final class MessageRules extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:validate.MessageRules)
    MessageRulesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageRules.newBuilder() to construct.
  private MessageRules(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageRules() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageRules();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.envoyproxy.pgv.validate.Validate.internal_static_validate_MessageRules_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.envoyproxy.pgv.validate.Validate.internal_static_validate_MessageRules_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.envoyproxy.pgv.validate.MessageRules.class, io.envoyproxy.pgv.validate.MessageRules.Builder.class);
  }

  private int bitField0_;
  public static final int SKIP_FIELD_NUMBER = 1;
  private boolean skip_;
  /**
   * <pre>
   * Skip specifies that the validation rules of this field should not be
   * evaluated
   * </pre>
   *
   * <code>optional bool skip = 1;</code>
   * @return Whether the skip field is set.
   */
  @java.lang.Override
  public boolean hasSkip() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Skip specifies that the validation rules of this field should not be
   * evaluated
   * </pre>
   *
   * <code>optional bool skip = 1;</code>
   * @return The skip.
   */
  @java.lang.Override
  public boolean getSkip() {
    return skip_;
  }

  public static final int REQUIRED_FIELD_NUMBER = 2;
  private boolean required_;
  /**
   * <pre>
   * Required specifies that this field must be set
   * </pre>
   *
   * <code>optional bool required = 2;</code>
   * @return Whether the required field is set.
   */
  @java.lang.Override
  public boolean hasRequired() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Required specifies that this field must be set
   * </pre>
   *
   * <code>optional bool required = 2;</code>
   * @return The required.
   */
  @java.lang.Override
  public boolean getRequired() {
    return required_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(1, skip_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBool(2, required_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, skip_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, required_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.envoyproxy.pgv.validate.MessageRules)) {
      return super.equals(obj);
    }
    io.envoyproxy.pgv.validate.MessageRules other = (io.envoyproxy.pgv.validate.MessageRules) obj;

    if (hasSkip() != other.hasSkip()) return false;
    if (hasSkip()) {
      if (getSkip()
          != other.getSkip()) return false;
    }
    if (hasRequired() != other.hasRequired()) return false;
    if (hasRequired()) {
      if (getRequired()
          != other.getRequired()) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSkip()) {
      hash = (37 * hash) + SKIP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSkip());
    }
    if (hasRequired()) {
      hash = (37 * hash) + REQUIRED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRequired());
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.envoyproxy.pgv.validate.MessageRules parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.envoyproxy.pgv.validate.MessageRules parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.envoyproxy.pgv.validate.MessageRules parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.envoyproxy.pgv.validate.MessageRules parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.envoyproxy.pgv.validate.MessageRules parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.envoyproxy.pgv.validate.MessageRules parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.envoyproxy.pgv.validate.MessageRules parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.envoyproxy.pgv.validate.MessageRules parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.envoyproxy.pgv.validate.MessageRules parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.envoyproxy.pgv.validate.MessageRules parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.envoyproxy.pgv.validate.MessageRules parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.envoyproxy.pgv.validate.MessageRules parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.envoyproxy.pgv.validate.MessageRules prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * MessageRules describe the constraints applied to embedded message values.
   * For message-type fields, validation is performed recursively.
   * </pre>
   *
   * Protobuf type {@code validate.MessageRules}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:validate.MessageRules)
      io.envoyproxy.pgv.validate.MessageRulesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.envoyproxy.pgv.validate.Validate.internal_static_validate_MessageRules_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.envoyproxy.pgv.validate.Validate.internal_static_validate_MessageRules_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.envoyproxy.pgv.validate.MessageRules.class, io.envoyproxy.pgv.validate.MessageRules.Builder.class);
    }

    // Construct using io.envoyproxy.pgv.validate.MessageRules.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      skip_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      required_ = false;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.envoyproxy.pgv.validate.Validate.internal_static_validate_MessageRules_descriptor;
    }

    @java.lang.Override
    public io.envoyproxy.pgv.validate.MessageRules getDefaultInstanceForType() {
      return io.envoyproxy.pgv.validate.MessageRules.getDefaultInstance();
    }

    @java.lang.Override
    public io.envoyproxy.pgv.validate.MessageRules build() {
      io.envoyproxy.pgv.validate.MessageRules result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.envoyproxy.pgv.validate.MessageRules buildPartial() {
      io.envoyproxy.pgv.validate.MessageRules result = new io.envoyproxy.pgv.validate.MessageRules(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.skip_ = skip_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.required_ = required_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.envoyproxy.pgv.validate.MessageRules) {
        return mergeFrom((io.envoyproxy.pgv.validate.MessageRules)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.envoyproxy.pgv.validate.MessageRules other) {
      if (other == io.envoyproxy.pgv.validate.MessageRules.getDefaultInstance()) return this;
      if (other.hasSkip()) {
        setSkip(other.getSkip());
      }
      if (other.hasRequired()) {
        setRequired(other.getRequired());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              skip_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              required_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean skip_ ;
    /**
     * <pre>
     * Skip specifies that the validation rules of this field should not be
     * evaluated
     * </pre>
     *
     * <code>optional bool skip = 1;</code>
     * @return Whether the skip field is set.
     */
    @java.lang.Override
    public boolean hasSkip() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Skip specifies that the validation rules of this field should not be
     * evaluated
     * </pre>
     *
     * <code>optional bool skip = 1;</code>
     * @return The skip.
     */
    @java.lang.Override
    public boolean getSkip() {
      return skip_;
    }
    /**
     * <pre>
     * Skip specifies that the validation rules of this field should not be
     * evaluated
     * </pre>
     *
     * <code>optional bool skip = 1;</code>
     * @param value The skip to set.
     * @return This builder for chaining.
     */
    public Builder setSkip(boolean value) {
      bitField0_ |= 0x00000001;
      skip_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Skip specifies that the validation rules of this field should not be
     * evaluated
     * </pre>
     *
     * <code>optional bool skip = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkip() {
      bitField0_ = (bitField0_ & ~0x00000001);
      skip_ = false;
      onChanged();
      return this;
    }

    private boolean required_ ;
    /**
     * <pre>
     * Required specifies that this field must be set
     * </pre>
     *
     * <code>optional bool required = 2;</code>
     * @return Whether the required field is set.
     */
    @java.lang.Override
    public boolean hasRequired() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Required specifies that this field must be set
     * </pre>
     *
     * <code>optional bool required = 2;</code>
     * @return The required.
     */
    @java.lang.Override
    public boolean getRequired() {
      return required_;
    }
    /**
     * <pre>
     * Required specifies that this field must be set
     * </pre>
     *
     * <code>optional bool required = 2;</code>
     * @param value The required to set.
     * @return This builder for chaining.
     */
    public Builder setRequired(boolean value) {
      bitField0_ |= 0x00000002;
      required_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required specifies that this field must be set
     * </pre>
     *
     * <code>optional bool required = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequired() {
      bitField0_ = (bitField0_ & ~0x00000002);
      required_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:validate.MessageRules)
  }

  // @@protoc_insertion_point(class_scope:validate.MessageRules)
  private static final io.envoyproxy.pgv.validate.MessageRules DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.envoyproxy.pgv.validate.MessageRules();
  }

  public static io.envoyproxy.pgv.validate.MessageRules getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<MessageRules>
      PARSER = new com.google.protobuf.AbstractParser<MessageRules>() {
    @java.lang.Override
    public MessageRules parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MessageRules> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MessageRules> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.envoyproxy.pgv.validate.MessageRules getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

