// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validate/validate.proto

package io.envoyproxy.pgv.validate;

public final class Validate {
  private Validate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(io.envoyproxy.pgv.validate.Validate.disabled);
    registry.add(io.envoyproxy.pgv.validate.Validate.ignored);
    registry.add(io.envoyproxy.pgv.validate.Validate.required);
    registry.add(io.envoyproxy.pgv.validate.Validate.rules);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public static final int DISABLED_FIELD_NUMBER = 1071;
  /**
   * <pre>
   * Disabled nullifies any validation rules for this message, including any
   * message fields associated with it that do support validation.
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> disabled = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int IGNORED_FIELD_NUMBER = 1072;
  /**
   * <pre>
   * Ignore skips generation of validation methods for this message.
   * </pre>
   *
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> ignored = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int REQUIRED_FIELD_NUMBER = 1071;
  /**
   * <pre>
   * Required ensures that exactly one the field options in a oneof is set;
   * validation fails if no fields in the oneof are set.
   * </pre>
   *
   * <code>extend .google.protobuf.OneofOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.OneofOptions,
      java.lang.Boolean> required = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int RULES_FIELD_NUMBER = 1071;
  /**
   * <pre>
   * Rules specify the validations to be performed on this field. By default,
   * no validation is performed against a field.
   * </pre>
   *
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      io.envoyproxy.pgv.validate.FieldRules> rules = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        io.envoyproxy.pgv.validate.FieldRules.class,
        io.envoyproxy.pgv.validate.FieldRules.getDefaultInstance());
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_FieldRules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_FieldRules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_FloatRules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_FloatRules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_DoubleRules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_DoubleRules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_Int32Rules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_Int32Rules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_Int64Rules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_Int64Rules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_UInt32Rules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_UInt32Rules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_UInt64Rules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_UInt64Rules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_SInt32Rules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_SInt32Rules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_SInt64Rules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_SInt64Rules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_Fixed32Rules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_Fixed32Rules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_Fixed64Rules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_Fixed64Rules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_SFixed32Rules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_SFixed32Rules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_SFixed64Rules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_SFixed64Rules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_BoolRules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_BoolRules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_StringRules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_StringRules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_BytesRules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_BytesRules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_EnumRules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_EnumRules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_MessageRules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_MessageRules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_RepeatedRules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_RepeatedRules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_MapRules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_MapRules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_AnyRules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_AnyRules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_DurationRules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_DurationRules_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_validate_TimestampRules_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_validate_TimestampRules_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027validate/validate.proto\022\010validate\032 goo" +
      "gle/protobuf/descriptor.proto\032\036google/pr" +
      "otobuf/duration.proto\032\037google/protobuf/t" +
      "imestamp.proto\"\230\007\n\nFieldRules\022\'\n\007message" +
      "\030\021 \001(\0132\026.validate.MessageRules\022%\n\005float\030" +
      "\001 \001(\0132\024.validate.FloatRulesH\000\022\'\n\006double\030" +
      "\002 \001(\0132\025.validate.DoubleRulesH\000\022%\n\005int32\030" +
      "\003 \001(\0132\024.validate.Int32RulesH\000\022%\n\005int64\030\004" +
      " \001(\0132\024.validate.Int64RulesH\000\022\'\n\006uint32\030\005" +
      " \001(\0132\025.validate.UInt32RulesH\000\022\'\n\006uint64\030" +
      "\006 \001(\0132\025.validate.UInt64RulesH\000\022\'\n\006sint32" +
      "\030\007 \001(\0132\025.validate.SInt32RulesH\000\022\'\n\006sint6" +
      "4\030\010 \001(\0132\025.validate.SInt64RulesH\000\022)\n\007fixe" +
      "d32\030\t \001(\0132\026.validate.Fixed32RulesH\000\022)\n\007f" +
      "ixed64\030\n \001(\0132\026.validate.Fixed64RulesH\000\022+" +
      "\n\010sfixed32\030\013 \001(\0132\027.validate.SFixed32Rule" +
      "sH\000\022+\n\010sfixed64\030\014 \001(\0132\027.validate.SFixed6" +
      "4RulesH\000\022#\n\004bool\030\r \001(\0132\023.validate.BoolRu" +
      "lesH\000\022\'\n\006string\030\016 \001(\0132\025.validate.StringR" +
      "ulesH\000\022%\n\005bytes\030\017 \001(\0132\024.validate.BytesRu" +
      "lesH\000\022#\n\004enum\030\020 \001(\0132\023.validate.EnumRules" +
      "H\000\022+\n\010repeated\030\022 \001(\0132\027.validate.Repeated" +
      "RulesH\000\022!\n\003map\030\023 \001(\0132\022.validate.MapRules" +
      "H\000\022!\n\003any\030\024 \001(\0132\022.validate.AnyRulesH\000\022+\n" +
      "\010duration\030\025 \001(\0132\027.validate.DurationRules" +
      "H\000\022-\n\ttimestamp\030\026 \001(\0132\030.validate.Timesta" +
      "mpRulesH\000B\006\n\004type\"\177\n\nFloatRules\022\r\n\005const" +
      "\030\001 \001(\002\022\n\n\002lt\030\002 \001(\002\022\013\n\003lte\030\003 \001(\002\022\n\n\002gt\030\004 " +
      "\001(\002\022\013\n\003gte\030\005 \001(\002\022\n\n\002in\030\006 \003(\002\022\016\n\006not_in\030\007" +
      " \003(\002\022\024\n\014ignore_empty\030\010 \001(\010\"\200\001\n\013DoubleRul" +
      "es\022\r\n\005const\030\001 \001(\001\022\n\n\002lt\030\002 \001(\001\022\013\n\003lte\030\003 \001" +
      "(\001\022\n\n\002gt\030\004 \001(\001\022\013\n\003gte\030\005 \001(\001\022\n\n\002in\030\006 \003(\001\022" +
      "\016\n\006not_in\030\007 \003(\001\022\024\n\014ignore_empty\030\010 \001(\010\"\177\n" +
      "\nInt32Rules\022\r\n\005const\030\001 \001(\005\022\n\n\002lt\030\002 \001(\005\022\013" +
      "\n\003lte\030\003 \001(\005\022\n\n\002gt\030\004 \001(\005\022\013\n\003gte\030\005 \001(\005\022\n\n\002" +
      "in\030\006 \003(\005\022\016\n\006not_in\030\007 \003(\005\022\024\n\014ignore_empty" +
      "\030\010 \001(\010\"\177\n\nInt64Rules\022\r\n\005const\030\001 \001(\003\022\n\n\002l" +
      "t\030\002 \001(\003\022\013\n\003lte\030\003 \001(\003\022\n\n\002gt\030\004 \001(\003\022\013\n\003gte\030" +
      "\005 \001(\003\022\n\n\002in\030\006 \003(\003\022\016\n\006not_in\030\007 \003(\003\022\024\n\014ign" +
      "ore_empty\030\010 \001(\010\"\200\001\n\013UInt32Rules\022\r\n\005const" +
      "\030\001 \001(\r\022\n\n\002lt\030\002 \001(\r\022\013\n\003lte\030\003 \001(\r\022\n\n\002gt\030\004 " +
      "\001(\r\022\013\n\003gte\030\005 \001(\r\022\n\n\002in\030\006 \003(\r\022\016\n\006not_in\030\007" +
      " \003(\r\022\024\n\014ignore_empty\030\010 \001(\010\"\200\001\n\013UInt64Rul" +
      "es\022\r\n\005const\030\001 \001(\004\022\n\n\002lt\030\002 \001(\004\022\013\n\003lte\030\003 \001" +
      "(\004\022\n\n\002gt\030\004 \001(\004\022\013\n\003gte\030\005 \001(\004\022\n\n\002in\030\006 \003(\004\022" +
      "\016\n\006not_in\030\007 \003(\004\022\024\n\014ignore_empty\030\010 \001(\010\"\200\001" +
      "\n\013SInt32Rules\022\r\n\005const\030\001 \001(\021\022\n\n\002lt\030\002 \001(\021" +
      "\022\013\n\003lte\030\003 \001(\021\022\n\n\002gt\030\004 \001(\021\022\013\n\003gte\030\005 \001(\021\022\n" +
      "\n\002in\030\006 \003(\021\022\016\n\006not_in\030\007 \003(\021\022\024\n\014ignore_emp" +
      "ty\030\010 \001(\010\"\200\001\n\013SInt64Rules\022\r\n\005const\030\001 \001(\022\022" +
      "\n\n\002lt\030\002 \001(\022\022\013\n\003lte\030\003 \001(\022\022\n\n\002gt\030\004 \001(\022\022\013\n\003" +
      "gte\030\005 \001(\022\022\n\n\002in\030\006 \003(\022\022\016\n\006not_in\030\007 \003(\022\022\024\n" +
      "\014ignore_empty\030\010 \001(\010\"\201\001\n\014Fixed32Rules\022\r\n\005" +
      "const\030\001 \001(\007\022\n\n\002lt\030\002 \001(\007\022\013\n\003lte\030\003 \001(\007\022\n\n\002" +
      "gt\030\004 \001(\007\022\013\n\003gte\030\005 \001(\007\022\n\n\002in\030\006 \003(\007\022\016\n\006not" +
      "_in\030\007 \003(\007\022\024\n\014ignore_empty\030\010 \001(\010\"\201\001\n\014Fixe" +
      "d64Rules\022\r\n\005const\030\001 \001(\006\022\n\n\002lt\030\002 \001(\006\022\013\n\003l" +
      "te\030\003 \001(\006\022\n\n\002gt\030\004 \001(\006\022\013\n\003gte\030\005 \001(\006\022\n\n\002in\030" +
      "\006 \003(\006\022\016\n\006not_in\030\007 \003(\006\022\024\n\014ignore_empty\030\010 " +
      "\001(\010\"\202\001\n\rSFixed32Rules\022\r\n\005const\030\001 \001(\017\022\n\n\002" +
      "lt\030\002 \001(\017\022\013\n\003lte\030\003 \001(\017\022\n\n\002gt\030\004 \001(\017\022\013\n\003gte" +
      "\030\005 \001(\017\022\n\n\002in\030\006 \003(\017\022\016\n\006not_in\030\007 \003(\017\022\024\n\014ig" +
      "nore_empty\030\010 \001(\010\"\202\001\n\rSFixed64Rules\022\r\n\005co" +
      "nst\030\001 \001(\020\022\n\n\002lt\030\002 \001(\020\022\013\n\003lte\030\003 \001(\020\022\n\n\002gt" +
      "\030\004 \001(\020\022\013\n\003gte\030\005 \001(\020\022\n\n\002in\030\006 \003(\020\022\016\n\006not_i" +
      "n\030\007 \003(\020\022\024\n\014ignore_empty\030\010 \001(\010\"\032\n\tBoolRul" +
      "es\022\r\n\005const\030\001 \001(\010\"\375\003\n\013StringRules\022\r\n\005con" +
      "st\030\001 \001(\t\022\013\n\003len\030\023 \001(\004\022\017\n\007min_len\030\002 \001(\004\022\017" +
      "\n\007max_len\030\003 \001(\004\022\021\n\tlen_bytes\030\024 \001(\004\022\021\n\tmi" +
      "n_bytes\030\004 \001(\004\022\021\n\tmax_bytes\030\005 \001(\004\022\017\n\007patt" +
      "ern\030\006 \001(\t\022\016\n\006prefix\030\007 \001(\t\022\016\n\006suffix\030\010 \001(" +
      "\t\022\020\n\010contains\030\t \001(\t\022\024\n\014not_contains\030\027 \001(" +
      "\t\022\n\n\002in\030\n \003(\t\022\016\n\006not_in\030\013 \003(\t\022\017\n\005email\030\014" +
      " \001(\010H\000\022\022\n\010hostname\030\r \001(\010H\000\022\014\n\002ip\030\016 \001(\010H\000" +
      "\022\016\n\004ipv4\030\017 \001(\010H\000\022\016\n\004ipv6\030\020 \001(\010H\000\022\r\n\003uri\030" +
      "\021 \001(\010H\000\022\021\n\007uri_ref\030\022 \001(\010H\000\022\021\n\007address\030\025 " +
      "\001(\010H\000\022\016\n\004uuid\030\026 \001(\010H\000\0220\n\020well_known_rege" +
      "x\030\030 \001(\0162\024.validate.KnownRegexH\000\022\024\n\006stric" +
      "t\030\031 \001(\010:\004true\022\024\n\014ignore_empty\030\032 \001(\010B\014\n\nw" +
      "ell_known\"\373\001\n\nBytesRules\022\r\n\005const\030\001 \001(\014\022" +
      "\013\n\003len\030\r \001(\004\022\017\n\007min_len\030\002 \001(\004\022\017\n\007max_len" +
      "\030\003 \001(\004\022\017\n\007pattern\030\004 \001(\t\022\016\n\006prefix\030\005 \001(\014\022" +
      "\016\n\006suffix\030\006 \001(\014\022\020\n\010contains\030\007 \001(\014\022\n\n\002in\030" +
      "\010 \003(\014\022\016\n\006not_in\030\t \003(\014\022\014\n\002ip\030\n \001(\010H\000\022\016\n\004i" +
      "pv4\030\013 \001(\010H\000\022\016\n\004ipv6\030\014 \001(\010H\000\022\024\n\014ignore_em" +
      "pty\030\016 \001(\010B\014\n\nwell_known\"L\n\tEnumRules\022\r\n\005" +
      "const\030\001 \001(\005\022\024\n\014defined_only\030\002 \001(\010\022\n\n\002in\030" +
      "\003 \003(\005\022\016\n\006not_in\030\004 \003(\005\".\n\014MessageRules\022\014\n" +
      "\004skip\030\001 \001(\010\022\020\n\010required\030\002 \001(\010\"\200\001\n\rRepeat" +
      "edRules\022\021\n\tmin_items\030\001 \001(\004\022\021\n\tmax_items\030" +
      "\002 \001(\004\022\016\n\006unique\030\003 \001(\010\022#\n\005items\030\004 \001(\0132\024.v" +
      "alidate.FieldRules\022\024\n\014ignore_empty\030\005 \001(\010" +
      "\"\243\001\n\010MapRules\022\021\n\tmin_pairs\030\001 \001(\004\022\021\n\tmax_" +
      "pairs\030\002 \001(\004\022\021\n\tno_sparse\030\003 \001(\010\022\"\n\004keys\030\004" +
      " \001(\0132\024.validate.FieldRules\022$\n\006values\030\005 \001" +
      "(\0132\024.validate.FieldRules\022\024\n\014ignore_empty" +
      "\030\006 \001(\010\"8\n\010AnyRules\022\020\n\010required\030\001 \001(\010\022\n\n\002" +
      "in\030\002 \003(\t\022\016\n\006not_in\030\003 \003(\t\"\273\002\n\rDurationRul" +
      "es\022\020\n\010required\030\001 \001(\010\022(\n\005const\030\002 \001(\0132\031.go" +
      "ogle.protobuf.Duration\022%\n\002lt\030\003 \001(\0132\031.goo" +
      "gle.protobuf.Duration\022&\n\003lte\030\004 \001(\0132\031.goo" +
      "gle.protobuf.Duration\022%\n\002gt\030\005 \001(\0132\031.goog" +
      "le.protobuf.Duration\022&\n\003gte\030\006 \001(\0132\031.goog" +
      "le.protobuf.Duration\022%\n\002in\030\007 \003(\0132\031.googl" +
      "e.protobuf.Duration\022)\n\006not_in\030\010 \003(\0132\031.go" +
      "ogle.protobuf.Duration\"\272\002\n\016TimestampRule" +
      "s\022\020\n\010required\030\001 \001(\010\022)\n\005const\030\002 \001(\0132\032.goo" +
      "gle.protobuf.Timestamp\022&\n\002lt\030\003 \001(\0132\032.goo" +
      "gle.protobuf.Timestamp\022\'\n\003lte\030\004 \001(\0132\032.go" +
      "ogle.protobuf.Timestamp\022&\n\002gt\030\005 \001(\0132\032.go" +
      "ogle.protobuf.Timestamp\022\'\n\003gte\030\006 \001(\0132\032.g" +
      "oogle.protobuf.Timestamp\022\016\n\006lt_now\030\007 \001(\010" +
      "\022\016\n\006gt_now\030\010 \001(\010\022)\n\006within\030\t \001(\0132\031.googl" +
      "e.protobuf.Duration*F\n\nKnownRegex\022\013\n\007UNK" +
      "NOWN\020\000\022\024\n\020HTTP_HEADER_NAME\020\001\022\025\n\021HTTP_HEA" +
      "DER_VALUE\020\002:2\n\010disabled\022\037.google.protobu" +
      "f.MessageOptions\030\257\010 \001(\010:1\n\007ignored\022\037.goo" +
      "gle.protobuf.MessageOptions\030\260\010 \001(\010:0\n\010re" +
      "quired\022\035.google.protobuf.OneofOptions\030\257\010" +
      " \001(\010:C\n\005rules\022\035.google.protobuf.FieldOpt" +
      "ions\030\257\010 \001(\0132\024.validate.FieldRulesBR\n\032io." +
      "envoyproxy.pgv.validateP\001Z2github.com/en" +
      "voyproxy/protoc-gen-validate/validate"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
          com.google.protobuf.DurationProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_validate_FieldRules_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_validate_FieldRules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_FieldRules_descriptor,
        new java.lang.String[] { "Message", "Float", "Double", "Int32", "Int64", "Uint32", "Uint64", "Sint32", "Sint64", "Fixed32", "Fixed64", "Sfixed32", "Sfixed64", "Bool", "String", "Bytes", "Enum", "Repeated", "Map", "Any", "Duration", "Timestamp", "Type", });
    internal_static_validate_FloatRules_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_validate_FloatRules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_FloatRules_descriptor,
        new java.lang.String[] { "Const", "Lt", "Lte", "Gt", "Gte", "In", "NotIn", "IgnoreEmpty", });
    internal_static_validate_DoubleRules_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_validate_DoubleRules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_DoubleRules_descriptor,
        new java.lang.String[] { "Const", "Lt", "Lte", "Gt", "Gte", "In", "NotIn", "IgnoreEmpty", });
    internal_static_validate_Int32Rules_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_validate_Int32Rules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_Int32Rules_descriptor,
        new java.lang.String[] { "Const", "Lt", "Lte", "Gt", "Gte", "In", "NotIn", "IgnoreEmpty", });
    internal_static_validate_Int64Rules_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_validate_Int64Rules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_Int64Rules_descriptor,
        new java.lang.String[] { "Const", "Lt", "Lte", "Gt", "Gte", "In", "NotIn", "IgnoreEmpty", });
    internal_static_validate_UInt32Rules_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_validate_UInt32Rules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_UInt32Rules_descriptor,
        new java.lang.String[] { "Const", "Lt", "Lte", "Gt", "Gte", "In", "NotIn", "IgnoreEmpty", });
    internal_static_validate_UInt64Rules_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_validate_UInt64Rules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_UInt64Rules_descriptor,
        new java.lang.String[] { "Const", "Lt", "Lte", "Gt", "Gte", "In", "NotIn", "IgnoreEmpty", });
    internal_static_validate_SInt32Rules_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_validate_SInt32Rules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_SInt32Rules_descriptor,
        new java.lang.String[] { "Const", "Lt", "Lte", "Gt", "Gte", "In", "NotIn", "IgnoreEmpty", });
    internal_static_validate_SInt64Rules_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_validate_SInt64Rules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_SInt64Rules_descriptor,
        new java.lang.String[] { "Const", "Lt", "Lte", "Gt", "Gte", "In", "NotIn", "IgnoreEmpty", });
    internal_static_validate_Fixed32Rules_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_validate_Fixed32Rules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_Fixed32Rules_descriptor,
        new java.lang.String[] { "Const", "Lt", "Lte", "Gt", "Gte", "In", "NotIn", "IgnoreEmpty", });
    internal_static_validate_Fixed64Rules_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_validate_Fixed64Rules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_Fixed64Rules_descriptor,
        new java.lang.String[] { "Const", "Lt", "Lte", "Gt", "Gte", "In", "NotIn", "IgnoreEmpty", });
    internal_static_validate_SFixed32Rules_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_validate_SFixed32Rules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_SFixed32Rules_descriptor,
        new java.lang.String[] { "Const", "Lt", "Lte", "Gt", "Gte", "In", "NotIn", "IgnoreEmpty", });
    internal_static_validate_SFixed64Rules_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_validate_SFixed64Rules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_SFixed64Rules_descriptor,
        new java.lang.String[] { "Const", "Lt", "Lte", "Gt", "Gte", "In", "NotIn", "IgnoreEmpty", });
    internal_static_validate_BoolRules_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_validate_BoolRules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_BoolRules_descriptor,
        new java.lang.String[] { "Const", });
    internal_static_validate_StringRules_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_validate_StringRules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_StringRules_descriptor,
        new java.lang.String[] { "Const", "Len", "MinLen", "MaxLen", "LenBytes", "MinBytes", "MaxBytes", "Pattern", "Prefix", "Suffix", "Contains", "NotContains", "In", "NotIn", "Email", "Hostname", "Ip", "Ipv4", "Ipv6", "Uri", "UriRef", "Address", "Uuid", "WellKnownRegex", "Strict", "IgnoreEmpty", "WellKnown", });
    internal_static_validate_BytesRules_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_validate_BytesRules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_BytesRules_descriptor,
        new java.lang.String[] { "Const", "Len", "MinLen", "MaxLen", "Pattern", "Prefix", "Suffix", "Contains", "In", "NotIn", "Ip", "Ipv4", "Ipv6", "IgnoreEmpty", "WellKnown", });
    internal_static_validate_EnumRules_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_validate_EnumRules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_EnumRules_descriptor,
        new java.lang.String[] { "Const", "DefinedOnly", "In", "NotIn", });
    internal_static_validate_MessageRules_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_validate_MessageRules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_MessageRules_descriptor,
        new java.lang.String[] { "Skip", "Required", });
    internal_static_validate_RepeatedRules_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_validate_RepeatedRules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_RepeatedRules_descriptor,
        new java.lang.String[] { "MinItems", "MaxItems", "Unique", "Items", "IgnoreEmpty", });
    internal_static_validate_MapRules_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_validate_MapRules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_MapRules_descriptor,
        new java.lang.String[] { "MinPairs", "MaxPairs", "NoSparse", "Keys", "Values", "IgnoreEmpty", });
    internal_static_validate_AnyRules_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_validate_AnyRules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_AnyRules_descriptor,
        new java.lang.String[] { "Required", "In", "NotIn", });
    internal_static_validate_DurationRules_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_validate_DurationRules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_DurationRules_descriptor,
        new java.lang.String[] { "Required", "Const", "Lt", "Lte", "Gt", "Gte", "In", "NotIn", });
    internal_static_validate_TimestampRules_descriptor =
      getDescriptor().getMessageTypes().get(22);
    internal_static_validate_TimestampRules_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_validate_TimestampRules_descriptor,
        new java.lang.String[] { "Required", "Const", "Lt", "Lte", "Gt", "Gte", "LtNow", "GtNow", "Within", });
    disabled.internalInit(descriptor.getExtensions().get(0));
    ignored.internalInit(descriptor.getExtensions().get(1));
    required.internalInit(descriptor.getExtensions().get(2));
    rules.internalInit(descriptor.getExtensions().get(3));
    com.google.protobuf.DescriptorProtos.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
