//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/deploy/v1/deploy.proto

package io.nitric.proto.deploy.v1;

@kotlin.jvm.JvmName("-initializedeployDownRequest")
inline fun deployDownRequest(block: io.nitric.proto.deploy.v1.DeployDownRequestKt.Dsl.() -> kotlin.Unit): io.nitric.proto.deploy.v1.DeployDownRequest =
  io.nitric.proto.deploy.v1.DeployDownRequestKt.Dsl._create(io.nitric.proto.deploy.v1.DeployDownRequest.newBuilder()).apply { block() }._build()
object DeployDownRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: io.nitric.proto.deploy.v1.DeployDownRequest.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.nitric.proto.deploy.v1.DeployDownRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.nitric.proto.deploy.v1.DeployDownRequest = _builder.build()

    /**
     * <pre>
     * A map of attributes related to the deploy request
     * this allows for adding project identifiers etc.
     * </pre>
     *
     * <code>.google.protobuf.Struct attributes = 1;</code>
     */
    var attributes: com.google.protobuf.Struct
      @JvmName("getAttributes")
      get() = _builder.getAttributes()
      @JvmName("setAttributes")
      set(value) {
        _builder.setAttributes(value)
      }
    /**
     * <pre>
     * A map of attributes related to the deploy request
     * this allows for adding project identifiers etc.
     * </pre>
     *
     * <code>.google.protobuf.Struct attributes = 1;</code>
     */
    fun clearAttributes() {
      _builder.clearAttributes()
    }
    /**
     * <pre>
     * A map of attributes related to the deploy request
     * this allows for adding project identifiers etc.
     * </pre>
     *
     * <code>.google.protobuf.Struct attributes = 1;</code>
     * @return Whether the attributes field is set.
     */
    fun hasAttributes(): kotlin.Boolean {
      return _builder.hasAttributes()
    }
  }
}
@kotlin.jvm.JvmSynthetic
inline fun io.nitric.proto.deploy.v1.DeployDownRequest.copy(block: io.nitric.proto.deploy.v1.DeployDownRequestKt.Dsl.() -> kotlin.Unit): io.nitric.proto.deploy.v1.DeployDownRequest =
  io.nitric.proto.deploy.v1.DeployDownRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

val io.nitric.proto.deploy.v1.DeployDownRequestOrBuilder.attributesOrNull: com.google.protobuf.Struct?
  get() = if (hasAttributes()) getAttributes() else null

