//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/resource/v1/resource.proto

package io.nitric.proto.resource.v1;

@kotlin.jvm.JvmName("-initializequeueResource")
inline fun queueResource(block: io.nitric.proto.resource.v1.QueueResourceKt.Dsl.() -> kotlin.Unit): io.nitric.proto.resource.v1.QueueResource =
  io.nitric.proto.resource.v1.QueueResourceKt.Dsl._create(io.nitric.proto.resource.v1.QueueResource.newBuilder()).apply { block() }._build()
object QueueResourceKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: io.nitric.proto.resource.v1.QueueResource.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.nitric.proto.resource.v1.QueueResource.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.nitric.proto.resource.v1.QueueResource = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
inline fun io.nitric.proto.resource.v1.QueueResource.copy(block: io.nitric.proto.resource.v1.QueueResourceKt.Dsl.() -> kotlin.Unit): io.nitric.proto.resource.v1.QueueResource =
  io.nitric.proto.resource.v1.QueueResourceKt.Dsl._create(this.toBuilder()).apply { block() }._build()

