// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/deploy/v1/deploy.proto

package io.nitric.proto.deploy.v1;

public interface BucketNotificationTargetOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.deploy.v1.BucketNotificationTarget)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.nitric.faas.v1.BucketNotificationConfig config = 1;</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <code>.nitric.faas.v1.BucketNotificationConfig config = 1;</code>
   * @return The config.
   */
  io.nitric.proto.faas.v1.BucketNotificationConfig getConfig();
  /**
   * <code>.nitric.faas.v1.BucketNotificationConfig config = 1;</code>
   */
  io.nitric.proto.faas.v1.BucketNotificationConfigOrBuilder getConfigOrBuilder();

  /**
   * <pre>
   * The name of an execution unit to target
   * </pre>
   *
   * <code>string execution_unit = 2;</code>
   * @return Whether the executionUnit field is set.
   */
  boolean hasExecutionUnit();
  /**
   * <pre>
   * The name of an execution unit to target
   * </pre>
   *
   * <code>string execution_unit = 2;</code>
   * @return The executionUnit.
   */
  java.lang.String getExecutionUnit();
  /**
   * <pre>
   * The name of an execution unit to target
   * </pre>
   *
   * <code>string execution_unit = 2;</code>
   * @return The bytes for executionUnit.
   */
  com.google.protobuf.ByteString
      getExecutionUnitBytes();

  public io.nitric.proto.deploy.v1.BucketNotificationTarget.TargetCase getTargetCase();
}
