// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/deploy/v1/deploy.proto

package io.nitric.proto.deploy.v1;

public interface SecretOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.deploy.v1.Secret)
    com.google.protobuf.MessageOrBuilder {
}
