// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/deploy/v1/deploy.proto

package io.nitric.proto.deploy.v1;

/**
 * Protobuf type {@code nitric.deploy.v1.Spec}
 */
public final class Spec extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:nitric.deploy.v1.Spec)
    SpecOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Spec.newBuilder() to construct.
  private Spec(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Spec() {
    resources_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Spec();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.nitric.proto.deploy.v1.Deploys.internal_static_nitric_deploy_v1_Spec_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.nitric.proto.deploy.v1.Deploys.internal_static_nitric_deploy_v1_Spec_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.nitric.proto.deploy.v1.Spec.class, io.nitric.proto.deploy.v1.Spec.Builder.class);
  }

  public static final int RESOURCES_FIELD_NUMBER = 1;
  private java.util.List<io.nitric.proto.deploy.v1.Resource> resources_;
  /**
   * <pre>
   * list of resources to deploy
   * </pre>
   *
   * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.nitric.proto.deploy.v1.Resource> getResourcesList() {
    return resources_;
  }
  /**
   * <pre>
   * list of resources to deploy
   * </pre>
   *
   * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.nitric.proto.deploy.v1.ResourceOrBuilder> 
      getResourcesOrBuilderList() {
    return resources_;
  }
  /**
   * <pre>
   * list of resources to deploy
   * </pre>
   *
   * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
   */
  @java.lang.Override
  public int getResourcesCount() {
    return resources_.size();
  }
  /**
   * <pre>
   * list of resources to deploy
   * </pre>
   *
   * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
   */
  @java.lang.Override
  public io.nitric.proto.deploy.v1.Resource getResources(int index) {
    return resources_.get(index);
  }
  /**
   * <pre>
   * list of resources to deploy
   * </pre>
   *
   * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
   */
  @java.lang.Override
  public io.nitric.proto.deploy.v1.ResourceOrBuilder getResourcesOrBuilder(
      int index) {
    return resources_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < resources_.size(); i++) {
      output.writeMessage(1, resources_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < resources_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, resources_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.nitric.proto.deploy.v1.Spec)) {
      return super.equals(obj);
    }
    io.nitric.proto.deploy.v1.Spec other = (io.nitric.proto.deploy.v1.Spec) obj;

    if (!getResourcesList()
        .equals(other.getResourcesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getResourcesCount() > 0) {
      hash = (37 * hash) + RESOURCES_FIELD_NUMBER;
      hash = (53 * hash) + getResourcesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.nitric.proto.deploy.v1.Spec parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nitric.proto.deploy.v1.Spec parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nitric.proto.deploy.v1.Spec parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nitric.proto.deploy.v1.Spec parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nitric.proto.deploy.v1.Spec parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.nitric.proto.deploy.v1.Spec parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.nitric.proto.deploy.v1.Spec parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.nitric.proto.deploy.v1.Spec parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.nitric.proto.deploy.v1.Spec parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.nitric.proto.deploy.v1.Spec parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.nitric.proto.deploy.v1.Spec parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.nitric.proto.deploy.v1.Spec parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.nitric.proto.deploy.v1.Spec prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code nitric.deploy.v1.Spec}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:nitric.deploy.v1.Spec)
      io.nitric.proto.deploy.v1.SpecOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.nitric.proto.deploy.v1.Deploys.internal_static_nitric_deploy_v1_Spec_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.nitric.proto.deploy.v1.Deploys.internal_static_nitric_deploy_v1_Spec_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.nitric.proto.deploy.v1.Spec.class, io.nitric.proto.deploy.v1.Spec.Builder.class);
    }

    // Construct using io.nitric.proto.deploy.v1.Spec.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (resourcesBuilder_ == null) {
        resources_ = java.util.Collections.emptyList();
      } else {
        resources_ = null;
        resourcesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.nitric.proto.deploy.v1.Deploys.internal_static_nitric_deploy_v1_Spec_descriptor;
    }

    @java.lang.Override
    public io.nitric.proto.deploy.v1.Spec getDefaultInstanceForType() {
      return io.nitric.proto.deploy.v1.Spec.getDefaultInstance();
    }

    @java.lang.Override
    public io.nitric.proto.deploy.v1.Spec build() {
      io.nitric.proto.deploy.v1.Spec result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.nitric.proto.deploy.v1.Spec buildPartial() {
      io.nitric.proto.deploy.v1.Spec result = new io.nitric.proto.deploy.v1.Spec(this);
      int from_bitField0_ = bitField0_;
      if (resourcesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          resources_ = java.util.Collections.unmodifiableList(resources_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.resources_ = resources_;
      } else {
        result.resources_ = resourcesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.nitric.proto.deploy.v1.Spec) {
        return mergeFrom((io.nitric.proto.deploy.v1.Spec)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.nitric.proto.deploy.v1.Spec other) {
      if (other == io.nitric.proto.deploy.v1.Spec.getDefaultInstance()) return this;
      if (resourcesBuilder_ == null) {
        if (!other.resources_.isEmpty()) {
          if (resources_.isEmpty()) {
            resources_ = other.resources_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResourcesIsMutable();
            resources_.addAll(other.resources_);
          }
          onChanged();
        }
      } else {
        if (!other.resources_.isEmpty()) {
          if (resourcesBuilder_.isEmpty()) {
            resourcesBuilder_.dispose();
            resourcesBuilder_ = null;
            resources_ = other.resources_;
            bitField0_ = (bitField0_ & ~0x00000001);
            resourcesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResourcesFieldBuilder() : null;
          } else {
            resourcesBuilder_.addAllMessages(other.resources_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.nitric.proto.deploy.v1.Resource m =
                  input.readMessage(
                      io.nitric.proto.deploy.v1.Resource.parser(),
                      extensionRegistry);
              if (resourcesBuilder_ == null) {
                ensureResourcesIsMutable();
                resources_.add(m);
              } else {
                resourcesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.nitric.proto.deploy.v1.Resource> resources_ =
      java.util.Collections.emptyList();
    private void ensureResourcesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        resources_ = new java.util.ArrayList<io.nitric.proto.deploy.v1.Resource>(resources_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.nitric.proto.deploy.v1.Resource, io.nitric.proto.deploy.v1.Resource.Builder, io.nitric.proto.deploy.v1.ResourceOrBuilder> resourcesBuilder_;

    /**
     * <pre>
     * list of resources to deploy
     * </pre>
     *
     * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
     */
    public java.util.List<io.nitric.proto.deploy.v1.Resource> getResourcesList() {
      if (resourcesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(resources_);
      } else {
        return resourcesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * list of resources to deploy
     * </pre>
     *
     * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
     */
    public int getResourcesCount() {
      if (resourcesBuilder_ == null) {
        return resources_.size();
      } else {
        return resourcesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * list of resources to deploy
     * </pre>
     *
     * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
     */
    public io.nitric.proto.deploy.v1.Resource getResources(int index) {
      if (resourcesBuilder_ == null) {
        return resources_.get(index);
      } else {
        return resourcesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * list of resources to deploy
     * </pre>
     *
     * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
     */
    public Builder setResources(
        int index, io.nitric.proto.deploy.v1.Resource value) {
      if (resourcesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResourcesIsMutable();
        resources_.set(index, value);
        onChanged();
      } else {
        resourcesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * list of resources to deploy
     * </pre>
     *
     * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
     */
    public Builder setResources(
        int index, io.nitric.proto.deploy.v1.Resource.Builder builderForValue) {
      if (resourcesBuilder_ == null) {
        ensureResourcesIsMutable();
        resources_.set(index, builderForValue.build());
        onChanged();
      } else {
        resourcesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * list of resources to deploy
     * </pre>
     *
     * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
     */
    public Builder addResources(io.nitric.proto.deploy.v1.Resource value) {
      if (resourcesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResourcesIsMutable();
        resources_.add(value);
        onChanged();
      } else {
        resourcesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * list of resources to deploy
     * </pre>
     *
     * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
     */
    public Builder addResources(
        int index, io.nitric.proto.deploy.v1.Resource value) {
      if (resourcesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResourcesIsMutable();
        resources_.add(index, value);
        onChanged();
      } else {
        resourcesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * list of resources to deploy
     * </pre>
     *
     * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
     */
    public Builder addResources(
        io.nitric.proto.deploy.v1.Resource.Builder builderForValue) {
      if (resourcesBuilder_ == null) {
        ensureResourcesIsMutable();
        resources_.add(builderForValue.build());
        onChanged();
      } else {
        resourcesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * list of resources to deploy
     * </pre>
     *
     * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
     */
    public Builder addResources(
        int index, io.nitric.proto.deploy.v1.Resource.Builder builderForValue) {
      if (resourcesBuilder_ == null) {
        ensureResourcesIsMutable();
        resources_.add(index, builderForValue.build());
        onChanged();
      } else {
        resourcesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * list of resources to deploy
     * </pre>
     *
     * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
     */
    public Builder addAllResources(
        java.lang.Iterable<? extends io.nitric.proto.deploy.v1.Resource> values) {
      if (resourcesBuilder_ == null) {
        ensureResourcesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, resources_);
        onChanged();
      } else {
        resourcesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * list of resources to deploy
     * </pre>
     *
     * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
     */
    public Builder clearResources() {
      if (resourcesBuilder_ == null) {
        resources_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        resourcesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * list of resources to deploy
     * </pre>
     *
     * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
     */
    public Builder removeResources(int index) {
      if (resourcesBuilder_ == null) {
        ensureResourcesIsMutable();
        resources_.remove(index);
        onChanged();
      } else {
        resourcesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * list of resources to deploy
     * </pre>
     *
     * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
     */
    public io.nitric.proto.deploy.v1.Resource.Builder getResourcesBuilder(
        int index) {
      return getResourcesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * list of resources to deploy
     * </pre>
     *
     * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
     */
    public io.nitric.proto.deploy.v1.ResourceOrBuilder getResourcesOrBuilder(
        int index) {
      if (resourcesBuilder_ == null) {
        return resources_.get(index);  } else {
        return resourcesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * list of resources to deploy
     * </pre>
     *
     * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
     */
    public java.util.List<? extends io.nitric.proto.deploy.v1.ResourceOrBuilder> 
         getResourcesOrBuilderList() {
      if (resourcesBuilder_ != null) {
        return resourcesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(resources_);
      }
    }
    /**
     * <pre>
     * list of resources to deploy
     * </pre>
     *
     * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
     */
    public io.nitric.proto.deploy.v1.Resource.Builder addResourcesBuilder() {
      return getResourcesFieldBuilder().addBuilder(
          io.nitric.proto.deploy.v1.Resource.getDefaultInstance());
    }
    /**
     * <pre>
     * list of resources to deploy
     * </pre>
     *
     * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
     */
    public io.nitric.proto.deploy.v1.Resource.Builder addResourcesBuilder(
        int index) {
      return getResourcesFieldBuilder().addBuilder(
          index, io.nitric.proto.deploy.v1.Resource.getDefaultInstance());
    }
    /**
     * <pre>
     * list of resources to deploy
     * </pre>
     *
     * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
     */
    public java.util.List<io.nitric.proto.deploy.v1.Resource.Builder> 
         getResourcesBuilderList() {
      return getResourcesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.nitric.proto.deploy.v1.Resource, io.nitric.proto.deploy.v1.Resource.Builder, io.nitric.proto.deploy.v1.ResourceOrBuilder> 
        getResourcesFieldBuilder() {
      if (resourcesBuilder_ == null) {
        resourcesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.nitric.proto.deploy.v1.Resource, io.nitric.proto.deploy.v1.Resource.Builder, io.nitric.proto.deploy.v1.ResourceOrBuilder>(
                resources_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        resources_ = null;
      }
      return resourcesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:nitric.deploy.v1.Spec)
  }

  // @@protoc_insertion_point(class_scope:nitric.deploy.v1.Spec)
  private static final io.nitric.proto.deploy.v1.Spec DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.nitric.proto.deploy.v1.Spec();
  }

  public static io.nitric.proto.deploy.v1.Spec getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Spec>
      PARSER = new com.google.protobuf.AbstractParser<Spec>() {
    @java.lang.Override
    public Spec parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Spec> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Spec> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.nitric.proto.deploy.v1.Spec getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

