// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/deploy/v1/deploy.proto

package io.nitric.proto.deploy.v1;

public interface SpecOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.deploy.v1.Spec)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * list of resources to deploy
   * </pre>
   *
   * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
   */
  java.util.List<io.nitric.proto.deploy.v1.Resource> 
      getResourcesList();
  /**
   * <pre>
   * list of resources to deploy
   * </pre>
   *
   * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
   */
  io.nitric.proto.deploy.v1.Resource getResources(int index);
  /**
   * <pre>
   * list of resources to deploy
   * </pre>
   *
   * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
   */
  int getResourcesCount();
  /**
   * <pre>
   * list of resources to deploy
   * </pre>
   *
   * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
   */
  java.util.List<? extends io.nitric.proto.deploy.v1.ResourceOrBuilder> 
      getResourcesOrBuilderList();
  /**
   * <pre>
   * list of resources to deploy
   * </pre>
   *
   * <code>repeated .nitric.deploy.v1.Resource resources = 1;</code>
   */
  io.nitric.proto.deploy.v1.ResourceOrBuilder getResourcesOrBuilder(
      int index);
}
