// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/websocket/v1/websocket.proto

package io.nitric.proto.websocket.v1;

public interface WebsocketCloseResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.websocket.v1.WebsocketCloseResponse)
    com.google.protobuf.MessageOrBuilder {
}
