// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/faas/v1/faas.proto

package io.nitric.proto.faas.v1;

public interface HttpWorkerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:nitric.faas.v1.HttpWorker)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The local port the server can be accessed on
   * </pre>
   *
   * <code>int32 port = 1;</code>
   * @return The port.
   */
  int getPort();
}
